QUESTION 1

using python lists

In [2]:
# Define matrices A, B, and C using lists
A = [[3.7827, 3.3454, 3.2341], [2.2122, 3.5678, 3.9087], [1.1234, 2.8934, 5.9087]]
B = [[3.1234, 3.0987, 3.1234], [2.1111, 3.2222, 3.3333], [1.0987, 1.3456, 5.1234]]
C = [[3.1243, 3.0989, 3.1256], [2.6721, 3.6785, 3.9017], [1.1254, 2.8956, 5.9187]]

# Function to add two matrices
def add_matrices(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[0])):
            row.append(matrix1[i][j] + matrix2[i][j])
        result.append(row)
    return result

# Function to subtract two matrices
def subtract_matrices(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[0])):
            row.append(matrix1[i][j] - matrix2[i][j])
        result.append(row)
    return result

# Function to multiply two matrices element-wise
def multiply_matrices(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[0])):
            row.append(matrix1[i][j] * matrix2[i][j])
        result.append(row)
    return result

# Perform addition, subtraction, and multiplication
A_plus_B = add_matrices(A, B)
A_minus_C = subtract_matrices(A, C)
A_multiply_B = multiply_matrices(A, B)

# Print the results
print("A + B =", A_plus_B)
print("A - C =", A_minus_C)
print("A * B (element-wise) =", A_multiply_B)

#profile the operation by list
import cProfile
def profile_list_operations():
    add_matrices(A, B)
    subtract_matrices(A, C)
    multiply_matrices(A, B)

cProfile.run('profile_list_operations()')


A + B = [[6.9061, 6.444100000000001, 6.3575], [4.3233, 6.79, 7.242], [2.2221, 4.239, 11.0321]]
A - C = [[0.6584000000000003, 0.24650000000000016, 0.10850000000000026], [-0.45989999999999975, -0.11070000000000002, 0.007000000000000117], [-0.0020000000000000018, -0.0021999999999997577, -0.010000000000000675]]
A * B (element-wise) = [[11.814885180000001, 10.36639098, 10.10138794], [4.6701754200000005, 11.49616516, 13.02886971], [1.23427958, 3.89335904, 30.27263358]]
         55 function calls in 0.000 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.000    0.000 2062688287.py:17(subtract_matrices)
        1    0.000    0.000    0.000    0.000 2062688287.py:27(multiply_matrices)
        1    0.000    0.000    0.000    0.000 2062688287.py:48(profile_list_operations)
        1    0.000    0.000    0.000    0.000 2062688287.py:7(add_matrices)
        1    0.000    0.000    0.000    0.000 <string>:1(

using numpy

In [3]:
import numpy as np

# Define matrices A, B, and C using numpy arrays
A = np.array([[3.7827, 3.3454, 3.2341], [2.2122, 3.5678, 3.9087], [1.1234, 2.8934, 5.9087]])
B = np.array([[3.1234, 3.0987, 3.1234], [2.1111, 3.2222, 3.3333], [1.0987, 1.3456, 5.1234]])
C = np.array([[3.1243, 3.0989, 3.1256], [2.6721, 3.6785, 3.9017], [1.1254, 2.8956, 5.9187]])


# Perform matrix addition, subtraction, and element-wise multiplication
def add_matrices(matrix1, matrix2):
    return matrix1 + matrix2
def subtract_matrices(matrix1, matrix2):
    return matrix1 - matrix2
def multiply_matrices(matrix1, matrix2):
    return matrix1 * matrix2
A_plus_B = A + B
A_minus_C = A - C
A_multiply_B = A * B

# Print the results
print("A + B =\n", A_plus_B)
print("\nA - C =\n", A_minus_C)
print("\nA * B (element-wise) =\n", A_multiply_B)

import cProfile
def profile_list_operations():
    add_matrices(A, B)
    subtract_matrices(A, C)
    multiply_matrices(A, B)

cProfile.run('profile_list_operations()')






A + B =
 [[ 6.9061  6.4441  6.3575]
 [ 4.3233  6.79    7.242 ]
 [ 2.2221  4.239  11.0321]]

A - C =
 [[ 0.6584  0.2465  0.1085]
 [-0.4599 -0.1107  0.007 ]
 [-0.002  -0.0022 -0.01  ]]

A * B (element-wise) =
 [[11.81488518 10.36639098 10.10138794]
 [ 4.67017542 11.49616516 13.02886971]
 [ 1.23427958  3.89335904 30.27263358]]
         7 function calls in 0.000 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.000    0.000 3697985544.py:10(add_matrices)
        1    0.000    0.000    0.000    0.000 3697985544.py:12(subtract_matrices)
        1    0.000    0.000    0.000    0.000 3697985544.py:14(multiply_matrices)
        1    0.000    0.000    0.000    0.000 3697985544.py:26(profile_list_operations)
        1    0.000    0.000    0.000    0.000 <string>:1(<module>)
        1    0.000    0.000    0.000    0.000 {built-in method builtins.exec}
        1    0.000    0.000    0.000    0.000 {method 

QUESTION 2

In [4]:
# I. Create a List
my_list = [1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]

# II. Iterate using a for loop
print("II. For loop iteration:")
for item in my_list:
    print(item)

# III. Iterate using for loop and range
print("\nIII. For loop and range:")
for i in range(len(my_list)):
    print(f"Index {i}: {my_list[i]}")

# IV. List Comprehension
print("\nIV. List Comprehension:")
squared_list = [x**2 for x in my_list]
print("Squared List:", squared_list)

# V. Enumerate
print("\nV. Enumerate:")
for index, value in enumerate(my_list):
    print(f"Index {index}: {value}")

# VI. Iter function and next function
print("\nVI. Iter and Next:")
my_iter = iter(my_list)
print(next(my_iter))  # First element
print(next(my_iter))  # Second element

# VII. Map function (e.g., multiply each element by 2)
print("\nVII. Map function:")
doubled_list = list(map(lambda x: x * 2, my_list))
print("Doubled List:", doubled_list)

# VIII. Using zip (Pair with another list)
print("\nVIII. Zip with another list:")
second_list = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
zipped_list = list(zip(my_list, second_list))
print("Zipped List:", zipped_list)

# IX. Using NumPy Module
import numpy as np
print("\nIX. Using NumPy:")
numpy_array = np.array(my_list)
numpy_squared = numpy_array ** 2
print("NumPy Squared Array:", numpy_squared)


II. For loop iteration:
1225
4986
6789
7890
2345
6783
987
1234
8765
3456

III. For loop and range:
Index 0: 1225
Index 1: 4986
Index 2: 6789
Index 3: 7890
Index 4: 2345
Index 5: 6783
Index 6: 987
Index 7: 1234
Index 8: 8765
Index 9: 3456

IV. List Comprehension:
Squared List: [1500625, 24860196, 46090521, 62252100, 5499025, 46009089, 974169, 1522756, 76825225, 11943936]

V. Enumerate:
Index 0: 1225
Index 1: 4986
Index 2: 6789
Index 3: 7890
Index 4: 2345
Index 5: 6783
Index 6: 987
Index 7: 1234
Index 8: 8765
Index 9: 3456

VI. Iter and Next:
1225
4986

VII. Map function:
Doubled List: [2450, 9972, 13578, 15780, 4690, 13566, 1974, 2468, 17530, 6912]

VIII. Zip with another list:
Zipped List: [(1225, 10), (4986, 20), (6789, 30), (7890, 40), (2345, 50), (6783, 60), (987, 70), (1234, 80), (8765, 90), (3456, 100)]

IX. Using NumPy:
NumPy Squared Array: [ 1500625 24860196 46090521 62252100  5499025 46009089   974169  1522756
 76825225 11943936]


QUESTION 3

In [1]:
def permutations(lst):
    # Base case: if list is empty, return an empty list
    if len(lst) == 0:
        return [[]]
    
    result = []
    for i in range(len(lst)):
        # Extract the current element
        elem = lst[i]
        # Remaining elements
        rest = lst[:i] + lst[i+1:]
        # Recursive call to get permutations of the remaining elements
        for perm in permutations(rest):
            result.append([elem] + perm)
    return result

def combinations(lst, n):
    # Base case: if n is 0, return an empty list
    if n == 0:
        return [[]]
    # Base case: if list is empty or n is greater than the length of the list
    if len(lst) == 0 or n > len(lst):
        return []
    
    result = []
    for i in range(len(lst)):
        # Extract the current element
        elem = lst[i]
        # Recursive call to get combinations of remaining elements
        for comb in combinations(lst[i+1:], n-1):
            result.append([elem] + comb)
    return result

# List to compute permutations and combinations for
elements = ['A', 'B', 'C', 'D', 'E']

# Compute all permutations
perm_results = permutations(elements)
print("Permutations:")
for perm in perm_results:
    print(perm)

# Compute all combinations for each possible length
print("\nCombinations:")
for r in range(1, len(elements) + 1):
    comb_results = combinations(elements, r)
    print(f"Length {r}:")
    for comb in comb_results:
        print(comb)


Permutations:
['A', 'B', 'C', 'D', 'E']
['A', 'B', 'C', 'E', 'D']
['A', 'B', 'D', 'C', 'E']
['A', 'B', 'D', 'E', 'C']
['A', 'B', 'E', 'C', 'D']
['A', 'B', 'E', 'D', 'C']
['A', 'C', 'B', 'D', 'E']
['A', 'C', 'B', 'E', 'D']
['A', 'C', 'D', 'B', 'E']
['A', 'C', 'D', 'E', 'B']
['A', 'C', 'E', 'B', 'D']
['A', 'C', 'E', 'D', 'B']
['A', 'D', 'B', 'C', 'E']
['A', 'D', 'B', 'E', 'C']
['A', 'D', 'C', 'B', 'E']
['A', 'D', 'C', 'E', 'B']
['A', 'D', 'E', 'B', 'C']
['A', 'D', 'E', 'C', 'B']
['A', 'E', 'B', 'C', 'D']
['A', 'E', 'B', 'D', 'C']
['A', 'E', 'C', 'B', 'D']
['A', 'E', 'C', 'D', 'B']
['A', 'E', 'D', 'B', 'C']
['A', 'E', 'D', 'C', 'B']
['B', 'A', 'C', 'D', 'E']
['B', 'A', 'C', 'E', 'D']
['B', 'A', 'D', 'C', 'E']
['B', 'A', 'D', 'E', 'C']
['B', 'A', 'E', 'C', 'D']
['B', 'A', 'E', 'D', 'C']
['B', 'C', 'A', 'D', 'E']
['B', 'C', 'A', 'E', 'D']
['B', 'C', 'D', 'A', 'E']
['B', 'C', 'D', 'E', 'A']
['B', 'C', 'E', 'A', 'D']
['B', 'C', 'E', 'D', 'A']
['B', 'D', 'A', 'C', 'E']
['B', 'D', 'A', 'E', 'C'

QUESTION 4

In [8]:
import itertools

# Define the lists A, B, C, D, E
A = ['A1', 'A2', 'A3']
B = ['B1', 'B2']
C = ['C1', 'C2', 'C3']
D = ['D1', 'D2', 'D3']
E = ['E1', 'E2']

# Combine all lists into one list for easier computation
l =['A', 'B', 'C', 'D', 'E']

# I. Compute all permutations (with all elements from the combined list)

def permutations(l):
    print("Permutations:")
    all_permutations = list(itertools.permutations(l))
    for perm in all_permutations:
        print(perm)

# II. Compute all combinations (choosing a fixed number of elements, e.g., 3)
def combinations(l,x):
    print("\nCombinations of 3 elements:")
    all_combinations = list(itertools.combinations(l, x))
    for comb in all_combinations:
        print(comb)
    
import cProfile
def profile_operations():
    permutations(l)
    combinations(l,3)

cProfile.run('profile_operations()')



Permutations:
('A', 'B', 'C', 'D', 'E')
('A', 'B', 'C', 'E', 'D')
('A', 'B', 'D', 'C', 'E')
('A', 'B', 'D', 'E', 'C')
('A', 'B', 'E', 'C', 'D')
('A', 'B', 'E', 'D', 'C')
('A', 'C', 'B', 'D', 'E')
('A', 'C', 'B', 'E', 'D')
('A', 'C', 'D', 'B', 'E')
('A', 'C', 'D', 'E', 'B')
('A', 'C', 'E', 'B', 'D')
('A', 'C', 'E', 'D', 'B')
('A', 'D', 'B', 'C', 'E')
('A', 'D', 'B', 'E', 'C')
('A', 'D', 'C', 'B', 'E')
('A', 'D', 'C', 'E', 'B')
('A', 'D', 'E', 'B', 'C')
('A', 'D', 'E', 'C', 'B')
('A', 'E', 'B', 'C', 'D')
('A', 'E', 'B', 'D', 'C')
('A', 'E', 'C', 'B', 'D')
('A', 'E', 'C', 'D', 'B')
('A', 'E', 'D', 'B', 'C')
('A', 'E', 'D', 'C', 'B')
('B', 'A', 'C', 'D', 'E')
('B', 'A', 'C', 'E', 'D')
('B', 'A', 'D', 'C', 'E')
('B', 'A', 'D', 'E', 'C')
('B', 'A', 'E', 'C', 'D')
('B', 'A', 'E', 'D', 'C')
('B', 'C', 'A', 'D', 'E')
('B', 'C', 'A', 'E', 'D')
('B', 'C', 'D', 'A', 'E')
('B', 'C', 'D', 'E', 'A')
('B', 'C', 'E', 'A', 'D')
('B', 'C', 'E', 'D', 'A')
('B', 'D', 'A', 'C', 'E')
('B', 'D', 'A', 'E', 'C'